// Copyright 2025 Interlynk.io
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package spdx3

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/interlynk-io/sbomasm/v2/pkg/logger"
	"github.com/interlynk-io/sbomasm/v2/pkg/sbom"
	spdx3model "github.com/interlynk-io/spdx-zen/model/v3.0.1"
	"github.com/interlynk-io/spdx-zen/parse"
	"sigs.k8s.io/release-utils/version"
)

const NOA = "NOASSERTION"

// loadBom parses an SPDX 3.0 JSON-LD file at path into a *parse.Document.
func loadBom(ctx context.Context, path string) (*parse.Document, error) {
	log := logger.FromContext(ctx)

	sbomDoc, err := sbom.Parser(ctx, path)
	if err != nil {
		return nil, err
	}

	spdx3Doc, ok := sbomDoc.(*sbom.SPDX3Document)
	if !ok {
		return nil, fmt.Errorf("expected SPDX 3.0 document, got %T", sbomDoc)
	}

	log.Debugf("loading SPDX 3.0 bom: %s", path)
	return spdx3Doc.Doc, nil
}

func utcNowTime() time.Time {
	return time.Now().UTC()
}

func cloneElement(src interface{}, dst interface{}) error {
	b, err := json.Marshal(src)
	if err != nil {
		return err
	}
	return json.Unmarshal(b, dst)
}

// composeNamespace generates a unique namespace for the output document.
func composeNamespace(docName string) string {
	u := uuid.New().String()
	return fmt.Sprintf("https://interlynk.io/spdxdocs/%s/%s", docName, u)
}

// genSpdxDocumentMetadata creates a new SpdxDocument for the merged output.
func genSpdxDocumentMetadata(ms *merge) (*parse.Document, error) {
	if ms == nil {
		return nil, fmt.Errorf("settings is required")
	}

	doc := &parse.Document{}

	spdxDoc := &spdx3model.SpdxDocument{}
	spdxDoc.SpdxID = composeNamespace(ms.settings.App.Name)
	spdxDoc.Name = ms.settings.App.Name

	// Set profile conformance
	spdxDoc.ProfileConformance = []spdx3model.ProfileIdentifierType{
		spdx3model.ProfileIdentifierTypeCore,
		spdx3model.ProfileIdentifierTypeSoftware,
	}

	doc.SpdxDocument = spdxDoc
	return doc, nil
}

// genCreationInfo creates a new CreationInfo for the merged document.
func genCreationInfo(ms *merge) (*spdx3model.CreationInfo, error) {
	ci := spdx3model.CreationInfo{}

	// Set spec version and creation time
	ci.SpecVersion = spdx3model.SpecVersion
	ci.Created = utcNowTime()

	// Build createdBy (Agents only: Persons + Organizations)
	var createdBy []spdx3model.Agent
	seenCreators := make(map[string]bool)

	// Add authors from CLI settings as Persons
	for _, author := range ms.settings.App.Authors {
		if author.Name == "" {
			continue
		}
		person := &spdx3model.Person{}
		person.SpdxID = fmt.Sprintf("https://interlynk.io/person/%s-%s", sanitizeForID(author.Name), uuid.New().String())
		person.Name = author.Name
		createdBy = append(createdBy, spdx3model.Agent{Element: person.Element})
		seenCreators[author.Name] = true
	}

	// Merge creators from input documents' CreationInfo
	for _, inDoc := range ms.in {
		if inDoc.CreationInfo == nil {
			continue
		}
		for _, agent := range inDoc.CreationInfo.CreatedBy {
			key := agent.Name
			if key == "" {
				key = agent.SpdxID
			}
			if _, exists := seenCreators[key]; !exists {
				seenCreators[key] = true
				createdBy = append(createdBy, agent)
			}
		}
	}

	ci.CreatedBy = createdBy

	// Build createdUsing (Tools only)
	tool := &spdx3model.Tool{}
	tool.SpdxID = fmt.Sprintf("https://interlynk.io/tool/sbomasm-%s", version.GetVersionInfo().GitVersion)
	tool.Name = "sbomasm"
	ci.CreatedUsing = []spdx3model.Tool{*tool}

	// Generate comment referencing all merged documents
	var docNames []string
	for _, inDoc := range ms.in {
		if inDoc.SpdxDocument != nil {
			docNames = append(docNames, inDoc.SpdxDocument.Name)
		}
	}
	if len(docNames) > 0 {
		ci.Comment = fmt.Sprintf("Generated by sbomasm (%s) using %s",
			version.GetVersionInfo().GitVersion, strings.Join(docNames, ", "))
	}

	return &ci, nil
}

// genPrimaryPackage creates a new primary Package from CLI app settings.
func genPrimaryPackage(ms *merge) (*spdx3model.Package, error) {
	pkg := &spdx3model.Package{}

	pkg.SpdxID = fmt.Sprintf("https://interlynk.io/package/root-%s", ms.rootPackageID)
	pkg.Name = ms.settings.App.Name
	pkg.PackageVersion = ms.settings.App.Version
	pkg.Description = ms.settings.App.Description
	pkg.CopyrightText = ms.settings.App.Copyright

	// Set primary purpose if valid
	if purpose, ok := spdx3_strings_to_purposes[ms.settings.App.PrimaryPurpose]; ok {
		pkg.PrimaryPurpose = spdx3model.SoftwarePurpose(purpose)
	}

	// Add supplier if provided
	if ms.settings.App.Supplier.Name != "" {
		org := &spdx3model.Organization{}
		org.SpdxID = fmt.Sprintf("https://interlynk.io/organization/%s-%s", sanitizeForID(ms.settings.App.Supplier.Name), uuid.New().String())
		org.Name = ms.settings.App.Supplier.Name
		pkg.SuppliedBy = &spdx3model.Agent{Element: org.Element}
	}

	// Add checksums if provided
	if len(ms.settings.App.Checksums) > 0 {
		for _, c := range ms.settings.App.Checksums {
			if c.Value == "" {
				continue
			}
			algo := spdx3model.HashAlgorithm(c.Algorithm)
			pkg.VerifiedUsing = append(pkg.VerifiedUsing, spdx3model.Hash{
				Algorithm: algo,
				HashValue: c.Value,
			})
		}
	}

	// Add PURL if provided
	if ms.settings.App.Purl != "" {
		pkg.ExternalIdentifier = append(pkg.ExternalIdentifier, spdx3model.ExternalIdentifier{
			ExternalIdentifierType: spdx3model.ExternalIdentifierTypePackageUrl,
			Identifier:             ms.settings.App.Purl,
		})
	}

	// Add CPE if provided
	if ms.settings.App.CPE != "" {
		cpeType := spdx3model.ExternalIdentifierTypeCpe23
		if strings.HasPrefix(ms.settings.App.CPE, "cpe:/") {
			cpeType = spdx3model.ExternalIdentifierTypeCpe22
		}
		pkg.ExternalIdentifier = append(pkg.ExternalIdentifier, spdx3model.ExternalIdentifier{
			ExternalIdentifierType: cpeType,
			Identifier:             ms.settings.App.CPE,
		})
	}

	// Set concluded license
	if ms.settings.App.License.Id != "" {
		// Will be handled via HAS_CONCLUDED_LICENSE relationship in future
	} else if ms.settings.App.License.Expression != "" {
		// Will be handled via license expression in future
	}

	return pkg, nil
}

// rootPackageInfo holds the SpdxID of the primary package from the primary SBOM.
type rootPackageInfo struct {
	DocSpdxID string
	SpdxID    string
}

func findPrimaryAndSecondaryIndices(docCount int) (int, []int) {
	primaryIdx := 0
	var secondaryIdxs []int
	for i := 1; i < docCount; i++ {
		secondaryIdxs = append(secondaryIdxs, i)
	}
	return primaryIdx, secondaryIdxs
}

// getRootElementPkgID returns the spdxId of the first rootElement package.
func getRootElementPkgID(doc *parse.Document) string {
	if doc.SpdxDocument == nil || len(doc.SpdxDocument.RootElement) == 0 {
		return ""
	}
	return doc.SpdxDocument.RootElement[0].SpdxID
}

// extractPrimaryPackage finds and clones the package referenced by the primary SBOM's RootElement.
func extractPrimaryPackage(doc *parse.Document) (*spdx3model.Package, error) {
	primaryPkgID := getRootElementPkgID(doc)
	if primaryPkgID == "" {
		return nil, fmt.Errorf("primary SBOM has no rootElement")
	}

	for _, pkg := range doc.Packages {
		if pkg.SpdxID == primaryPkgID {
			clone := &spdx3model.Package{}
			if err := cloneElement(pkg, clone); err != nil {
				return nil, err
			}
			return clone, nil
		}
	}

	return nil, fmt.Errorf("primary package %s not found in primary SBOM", primaryPkgID)
}

// initOutDocFromPrimarySBOM initializes the output document metadata from the primary SBOM.
func initOutDocFromPrimarySBOM(m *merge, primaryDoc *parse.Document) (*parse.Document, error) {
	doc := &parse.Document{}

	spdxDoc := &spdx3model.SpdxDocument{}
	if primaryDoc.SpdxDocument != nil {
		spdxDoc.SpdxID = primaryDoc.SpdxDocument.SpdxID
		spdxDoc.Name = primaryDoc.SpdxDocument.Name
		spdxDoc.ProfileConformance = primaryDoc.SpdxDocument.ProfileConformance
	} else {
		spdxDoc.SpdxID = composeNamespace(m.settings.App.Name)
		spdxDoc.Name = m.settings.App.Name
	}

	doc.SpdxDocument = spdxDoc
	return doc, nil
}

// initCreationInfoFromPrimarySBOM initializes creation info preserving the primary SBOM's creators.
func initCreationInfoFromPrimarySBOM(m *merge, primaryDoc *parse.Document) (*spdx3model.CreationInfo, error) {
	ci := spdx3model.CreationInfo{}

	// Set spec version and update timestamp
	ci.SpecVersion = spdx3model.SpecVersion
	ci.Created = utcNowTime()

	// Generate comment referencing all merged documents
	var docNames []string
	for _, inDoc := range m.in {
		if inDoc.SpdxDocument != nil {
			docNames = append(docNames, inDoc.SpdxDocument.Name)
		}
	}

	sbomasmComment := fmt.Sprintf("Generated by sbomasm (%s) using %s",
		version.GetVersionInfo().GitVersion, strings.Join(docNames, ", "))

	if primaryDoc.SpdxDocument != nil {
		primaryCI := &primaryDoc.SpdxDocument.CreationInfo
		if primaryCI.Comment != "" {
			ci.Comment = primaryCI.Comment + "\n" + sbomasmComment
		} else {
			ci.Comment = sbomasmComment
		}
	} else {
		ci.Comment = sbomasmComment
	}

	// Preserve primary's creators (Agents only)
	var creators []spdx3model.Agent
	if primaryDoc.CreationInfo != nil {
		for _, agent := range primaryDoc.CreationInfo.CreatedBy {
			if agent.Name == "" {
				continue
			}
			creators = append(creators, agent)
		}
	}

	// Deduplicate creators by name
	seen := make(map[string]bool)
	var finalCreators []spdx3model.Agent
	for _, c := range creators {
		if _, ok := seen[c.Name]; ok {
			continue
		}
		seen[c.Name] = true
		finalCreators = append(finalCreators, c)
	}

	ci.CreatedBy = finalCreators

	// Build createdUsing (Tools only)
	tool := &spdx3model.Tool{}
	tool.SpdxID = fmt.Sprintf("https://interlynk.io/tool/sbomasm-%s", version.GetVersionInfo().GitVersion)
	tool.Name = "sbomasm"
	ci.CreatedUsing = []spdx3model.Tool{*tool}

	return &ci, nil
}

// getSecondaryDescribedPkgs returns the described packages from secondary SBOMs only.
func getSecondaryDescribedPkgs(docs []*parse.Document, secondaryIdxs []int) []string {
	var pkgs []string
	for _, idx := range secondaryIdxs {
		doc := docs[idx]
		if doc.SpdxDocument == nil || len(doc.SpdxDocument.RootElement) == 0 {
			continue
		}
		rootID := doc.SpdxDocument.RootElement[0].SpdxID
		if rootID != "" {
			pkgs = append(pkgs, rootID)
		}
	}
	return pkgs
}

// getDescribedPkgs returns all described (primary) package IDs from all input SBOMs.
func getDescribedPkgs(ms *merge) []string {
	var pkgs []string
	for _, doc := range ms.in {
		if doc.SpdxDocument == nil || len(doc.SpdxDocument.RootElement) == 0 {
			continue
		}
		rootID := doc.SpdxDocument.RootElement[0].SpdxID
		if rootID != "" {
			pkgs = append(pkgs, rootID)
		}
	}
	return pkgs
}

// createLookupKey creates a lookup key for deduplication.
func createLookupKey(spdxId string) string {
	return spdxId
}

// genPackageList merges packages from all input documents, deduplicating by name+version.
func genPackageList(ms *merge) ([]*spdx3model.Package, map[string]string, error) {
	return genPackageListWithRoot(ms, nil)
}

// genPackageListWithRoot merges packages with optional root package info for ID preservation.
func genPackageListWithRoot(ms *merge, rootPkgInfo *rootPackageInfo) ([]*spdx3model.Package, map[string]string, error) {
	var pkgs []*spdx3model.Package
	mapper := make(map[string]string)
	seen := make(map[string]string)

	for _, doc := range ms.in {
		for _, pkg := range doc.Packages {
			if pkg == nil {
				continue
			}

			key := fmt.Sprintf("%s-%s", strings.ToLower(pkg.Name), strings.ToLower(pkg.PackageVersion))

			// Check if this is the root package from the primary SBOM
			isRootPkg := rootPkgInfo != nil && pkg.SpdxID == rootPkgInfo.SpdxID

			// If already seen, map the old spdxId to the new spdxId
			if newID, exists := seen[key]; exists {
				mapper[pkg.SpdxID] = newID
				continue
			}

			clone := &spdx3model.Package{}
			if err := cloneElement(pkg, clone); err != nil {
				return nil, nil, err
			}

			var newSpdxID string
			if isRootPkg {
				newSpdxID = fmt.Sprintf("https://interlynk.io/package/root-%s", ms.rootPackageID)
			} else {
				newSpdxID = fmt.Sprintf("https://interlynk.io/package/%s-%s", sanitizeForID(pkg.Name), uuid.New().String())
			}

			mapper[pkg.SpdxID] = newSpdxID
			seen[key] = newSpdxID
			clone.SpdxID = newSpdxID

			// Reset creation info to share the output document's
			if ms.out != nil && ms.out.CreationInfo != nil {
				clone.CreationInfo = *ms.out.CreationInfo
			}

			pkgs = append(pkgs, clone)
		}
	}

	return pkgs, mapper, nil
}

// genFileList merges files from all input documents.
func genFileList(ms *merge) ([]*spdx3model.File, map[string]string, error) {
	var files []*spdx3model.File
	mapper := make(map[string]string)

	for _, doc := range ms.in {
		for _, file := range doc.Files {
			if file == nil {
				continue
			}

			clone := &spdx3model.File{}
			if err := cloneElement(file, clone); err != nil {
				return nil, nil, err
			}

			newSpdxID := fmt.Sprintf("https://interlynk.io/file/%s-%s", sanitizeForID(file.Name), uuid.New().String())
			mapper[file.SpdxID] = newSpdxID
			clone.SpdxID = newSpdxID

			if ms.out != nil && ms.out.CreationInfo != nil {
				clone.CreationInfo = *ms.out.CreationInfo
			}

			files = append(files, clone)
		}
	}

	return files, mapper, nil
}

// genRelationshipList merges relationships from all input documents, rewriting From/To references.
func genRelationshipList(ms *merge, pkgMapper map[string]string, fileMapper map[string]string) ([]*spdx3model.Relationship, error) {
	var relationships []*spdx3model.Relationship
	seen := make(map[string]bool)

	for _, doc := range ms.in {
		for _, rel := range doc.Relationships {
			if rel == nil {
				continue
			}

			// Skip DESCRIBES relationships from input SBOMs
			if rel.RelationshipType == spdx3model.RelationshipTypeDescribes {
				continue
			}

			clone := &spdx3model.Relationship{}
			if err := cloneElement(rel, clone); err != nil {
				return nil, err
			}

			// Rewrite From reference
			if newID, ok := pkgMapper[rel.From.SpdxID]; ok {
				clone.From.SpdxID = newID
			} else if newID, ok := fileMapper[rel.From.SpdxID]; ok {
				clone.From.SpdxID = newID
			}

			// Rewrite To references
			for i := range clone.To {
				if newID, ok := pkgMapper[clone.To[i].SpdxID]; ok {
					clone.To[i].SpdxID = newID
				} else if newID, ok := fileMapper[clone.To[i].SpdxID]; ok {
					clone.To[i].SpdxID = newID
				}
			}

			// Generate new spdxId for the relationship
			clone.SpdxID = fmt.Sprintf("https://interlynk.io/relationship/%s-%s-%s",
				string(clone.RelationshipType), sanitizeForID(clone.From.SpdxID), uuid.New().String())

			// Deduplicate relationships by content
			dedupKey := fmt.Sprintf("%s:%s:%s", clone.From.SpdxID, clone.RelationshipType, elementsKey(clone.To))
			if seen[dedupKey] {
				continue
			}
			seen[dedupKey] = true

			if ms.out != nil && ms.out.CreationInfo != nil {
				clone.CreationInfo = *ms.out.CreationInfo
			}

			relationships = append(relationships, clone)
		}
	}

	return relationships, nil
}

// elementsKey generates a deduplication key for a slice of elements.
func elementsKey(els []spdx3model.Element) string {
	var ids []string
	for _, el := range els {
		ids = append(ids, el.SpdxID)
	}
	return strings.Join(ids, ",")
}

// genAgentList merges agents (Organizations, Persons, Tools) from all input documents.
func genAgentList(ms *merge) (*agentCollection, error) {
	agents := &agentCollection{}
	seenOrgs := make(map[string]bool)
	seenPersons := make(map[string]bool)
	seenTools := make(map[string]bool)

	for _, doc := range ms.in {
		for _, org := range doc.Organizations {
			if org == nil {
				continue
			}
			key := org.Name
			if seenOrgs[key] {
				continue
			}
			seenOrgs[key] = true
			clone := &spdx3model.Organization{}
			if err := cloneElement(org, clone); err != nil {
				return nil, err
			}
			clone.SpdxID = fmt.Sprintf("https://interlynk.io/organization/%s-%s", sanitizeForID(org.Name), uuid.New().String())
			if ms.out != nil && ms.out.CreationInfo != nil {
				clone.CreationInfo = *ms.out.CreationInfo
			}
			agents.Organizations = append(agents.Organizations, clone)
		}

		for _, person := range doc.Persons {
			if person == nil {
				continue
			}
			key := person.Name
			if seenPersons[key] {
				continue
			}
			seenPersons[key] = true
			clone := &spdx3model.Person{}
			if err := cloneElement(person, clone); err != nil {
				return nil, err
			}
			clone.SpdxID = fmt.Sprintf("https://interlynk.io/person/%s-%s", sanitizeForID(person.Name), uuid.New().String())
			if ms.out != nil && ms.out.CreationInfo != nil {
				clone.CreationInfo = *ms.out.CreationInfo
			}
			agents.Persons = append(agents.Persons, clone)
		}

		for _, tool := range doc.Tools {
			if tool == nil {
				continue
			}
			key := tool.Name
			if seenTools[key] {
				continue
			}
			seenTools[key] = true
			clone := &spdx3model.Tool{}
			if err := cloneElement(tool, clone); err != nil {
				return nil, err
			}
			clone.SpdxID = fmt.Sprintf("https://interlynk.io/tool/%s-%s", sanitizeForID(tool.Name), uuid.New().String())
			if ms.out != nil && ms.out.CreationInfo != nil {
				clone.CreationInfo = *ms.out.CreationInfo
			}
			agents.Tools = append(agents.Tools, clone)
		}
	}

	return agents, nil
}

// genHierarchicalContains generates CONTAINS relationships between each input SBOM's
// primary package and its non-primary packages.
func genHierarchicalContains(ms *merge, pkgMapper map[string]string, ci *spdx3model.CreationInfo) []*spdx3model.Relationship {
	log := logger.FromContext(*ms.settings.Ctx)
	var newRels []*spdx3model.Relationship
	seenPairs := make(map[string]bool)

	if ci == nil {
		return newRels
	}

	for _, doc := range ms.in {
		if doc.SpdxDocument == nil || len(doc.SpdxDocument.RootElement) == 0 {
			continue
		}

		primaryID := doc.SpdxDocument.RootElement[0].SpdxID
		mappedPrimaryID, found := pkgMapper[primaryID]
		if !found {
			log.Warnf("could not find mapped primary package %s", primaryID)
			continue
		}

		for _, pkg := range doc.Packages {
			if pkg == nil || pkg.SpdxID == primaryID {
				continue
			}

			childID, found := pkgMapper[pkg.SpdxID]
			if !found {
				continue
			}

			pairKey := fmt.Sprintf("%s->%s", mappedPrimaryID, childID)
			if seenPairs[pairKey] {
				continue
			}
			seenPairs[pairKey] = true

			newRels = append(newRels, &spdx3model.Relationship{
				Element: spdx3model.Element{
					SpdxID:       fmt.Sprintf("https://interlynk.io/relationship/contains-%s", uuid.New().String()),
					Name:         "contains relationship",
					CreationInfo: *ci,
				},
				From:             spdx3model.Element{SpdxID: mappedPrimaryID},
				To:               []spdx3model.Element{{SpdxID: childID}},
				RelationshipType: spdx3model.RelationshipTypeContains,
			})
		}
	}

	log.Debugf("generated %d CONTAINS relationships for hierarchical merge", len(newRels))
	return newRels
}

func writeSBOM(doc *parse.Document, m *merge) error {
	log := logger.FromContext(*m.settings.Ctx)
	var w io.Writer
	outName := "stdout"

	if m.settings.Output.File == "" {
		w = os.Stdout
	} else {
		outName = m.settings.Output.File
		file, err := os.Create(m.settings.Output.File)
		if err != nil {
			return err
		}
		defer file.Close()
		w = file
	}

	wrapper := &sbom.SPDX3Document{Doc: doc}
	if err := sbom.WriteSBOM(w, wrapper); err != nil {
		return fmt.Errorf("failed to write SPDX 3.0 SBOM: %w", err)
	}

	log.Debugf("wrote SPDX 3.0 sbom to %s with packages:%d, files:%d, relationships:%d, orgs:%d, persons:%d, tools:%d",
		outName, len(doc.Packages), len(doc.Files), len(doc.Relationships),
		len(doc.Organizations), len(doc.Persons), len(doc.Tools))

	return nil
}

// sanitizeForID replaces characters that are problematic in URIs.
func sanitizeForID(s string) string {
	s = strings.ToLower(s)
	s = strings.ReplaceAll(s, " ", "-")
	s = strings.ReplaceAll(s, "/", "-")
	s = strings.ReplaceAll(s, "\\", "-")
	s = strings.ReplaceAll(s, ".", "-")
	s = strings.ReplaceAll(s, "_", "-")
	return s
}
