// Copyright 2026 Interlynk.io
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cmd

import (
	"context"
	"fmt"
	"strings"

	"github.com/interlynk-io/sbomasm/v2/pkg/generate/gsbom"
	"github.com/interlynk-io/sbomasm/v2/pkg/logger"
	"github.com/spf13/cobra"
)

// generateSbomCmd represents the generate sbom command
var generateSbomCmd = &cobra.Command{
	Use:          "sbom",
	Short:        "Generate SBOM from component metadata",
	Long:         "Generate an SBOM from component manifests and artifact metadata",
	SilenceUsage: true,
	Args:         cobra.NoArgs,
	RunE: func(cmd *cobra.Command, _ []string) error {
		// Logger setup
		debug, _ := cmd.Flags().GetBool("debug")
		if debug {
			logger.InitDebugLogger()
		} else {
			logger.InitProdLogger()
		}

		ctx := logger.WithLogger(context.Background())

		// extract generate sbom Params` from flags
		params, err := extractGenerateSBOM(cmd)
		if err != nil {
			return err
		}

		if err := validateGenerateSBOMParams(params); err != nil {
			return err
		}

		params.Ctx = &ctx
		return gsbom.Generate(params)
	},
}

// extractGenerateSBOM extracts the parameters for the
// generate sbom command from the command flags
func extractGenerateSBOM(cmd *cobra.Command) (*gsbom.GenerateSBOMParams, error) {
	params := gsbom.NewGenerateSBOMParams()

	params.ConfigPath, _ = cmd.Flags().GetString("config")
	params.InputFiles, _ = cmd.Flags().GetStringSlice("input")
	params.Output, _ = cmd.Flags().GetString("output")
	params.Tags = normalizeTags(getStringSliceFlag(cmd, "tags"))
	params.ExcludeTags = normalizeTags(getStringSliceFlag(cmd, "exclude-tags"))
	params.Format, _ = cmd.Flags().GetString("format")
	params.RecursePath, _ = cmd.Flags().GetString("recurse")
	params.Filename, _ = cmd.Flags().GetString("filename")

	return params, nil
}
func validateGenerateSBOMParams(params *gsbom.GenerateSBOMParams) error {
	if hasOverlap(params.Tags, params.ExcludeTags) {
		return fmt.Errorf("conflicting tags: same tag in include and exclude")
	}

	if params.Format != "cdx" && params.Format != "spdx" && params.Format != "cyclonedx" {
		return fmt.Errorf("invalid format: must be 'cyclonedx', 'cdx', or 'spdx'")
	}

	return nil
}

func normalizeTags(tags []string) []string {
	var normalized []string
	for _, tag := range tags {
		ttag := strings.TrimSpace(tag)
		if ttag != "" {
			normalized = append(normalized, strings.ToLower(ttag))
		}
	}
	return normalized
}

// getStringSliceFlag safely gets a string slice flag, ignoring the error.
func getStringSliceFlag(cmd *cobra.Command, name string) []string {
	val, _ := cmd.Flags().GetStringSlice(name)
	return val
}

func init() {
	// Flags
	generateSbomCmd.Flags().StringP("config", "c", ".artifact-metadata.yaml", "path to artifact metadata config, required, generated by (sbomasm generate config) command.")
	generateSbomCmd.Flags().StringSliceP("input", "i", []string{}, "paths to component metadata files (JSON or CSV). Can be specified multiple times.")
	generateSbomCmd.Flags().StringP("output", "o", "", "output SBOM file path (default stdout)")
	generateSbomCmd.Flags().StringSliceP("tags", "t", []string{}, "include components with any of these tags (default all)")
	generateSbomCmd.Flags().StringSlice("exclude-tags", []string{}, "exclude components with any of these tags (default none)")
	generateSbomCmd.Flags().String("format", "cyclonedx", "output SBOM format (cyclonedx or spdx)")
	generateSbomCmd.Flags().StringP("recurse", "r", "", "recursively discover component manifest files under the given directory")
	generateSbomCmd.Flags().String("filename", ".components.json", "filename to look for during recursive discovery (e.g. my-deps.json)")
	generateSbomCmd.Flags().Bool("debug", false, "enable debug logging")
}

func hasOverlap(include, exclude []string) bool {
	set := make(map[string]bool)
	for _, v := range include {
		set[strings.ToLower(v)] = true
	}
	for _, v := range exclude {
		if set[strings.ToLower(v)] {
			return true
		}
	}
	return false
}
